import React from 'react';
import { Download, BookOpen } from 'lucide-react';
import {
  OllamaIcon,
  OpenAIIcon,
  ClaudeIcon,
  OpenClawIcon,
  VSCodeIcon,
  CursorIcon,
  SlackIcon,
  MCPIcon } from
'./BrandIcons';
const integrations = [
{
  name: 'Ollama',
  Icon: OllamaIcon
},
{
  name: 'Codex',
  Icon: OpenAIIcon
},
{
  name: 'Claude Code',
  Icon: ClaudeIcon
},
{
  name: 'OpenClaw',
  Icon: OpenClawIcon
},
{
  name: 'VS Code',
  Icon: VSCodeIcon
},
{
  name: 'Cursor',
  Icon: CursorIcon
},
{
  name: 'Slack',
  Icon: SlackIcon
},
{
  name: 'MCP',
  Icon: MCPIcon
}];

export function Hero() {
  return (
    <div className="relative overflow-hidden bg-slate-50 pt-16 pb-24 lg:pt-24 lg:pb-32">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <div className="text-center max-w-4xl mx-auto">
          <div className="inline-flex items-center rounded-full px-3 py-1 text-sm font-medium text-brand-purple bg-purple-100 mb-8 border border-purple-200">
            Local-first · Open source · For humans and agents
          </div>

          <h1 className="text-5xl md:text-6xl font-extrabold tracking-tight text-slate-900 mb-6 leading-tight">
            Let your AI agents <br className="hidden md:block" />
            <span className="text-gradient">document the work</span> for you.
          </h1>

          <p className="mt-4 text-xl text-slate-600 mb-10 max-w-3xl mx-auto leading-relaxed">
            Mianotes gives Codex, Claude Code, Cursor, VS Code, Slack, and local
            agents a local-first workspace for documenting their work in
            Markdown. Everything stays private, portable, readable, and under
            your control, whether you run it on your computer or your own
            server.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-3">
            <button className="w-full sm:w-auto inline-flex items-center justify-center px-8 py-3.5 text-base font-medium text-white bg-brand-purple hover:bg-purple-600 rounded-xl transition-all shadow-lg shadow-purple-500/25 gap-2">
              <Download className="w-5 h-5" />
              Download Mianotes
            </button>
            <button className="w-full sm:w-auto inline-flex items-center justify-center px-8 py-3.5 text-base font-medium text-slate-700 bg-white hover:bg-slate-50 border border-slate-200 rounded-xl transition-all shadow-sm gap-2">
              <BookOpen className="w-5 h-5 text-slate-400" />
              Read the docs
            </button>
          </div>
          <p className="text-sm text-slate-500 italic mb-16">
            These docs were generated by Codex using Mianotes.
          </p>

          {/* Trust Row */}
          <div className="pt-8 border-t border-slate-200/60">
            <p className="text-sm font-medium text-slate-500 mb-6 uppercase tracking-wider">
              Works seamlessly with
            </p>
            <div className="flex flex-wrap justify-center items-center gap-x-6 gap-y-3 text-slate-700">
              {integrations.map(({ name, Icon }) =>
              <div
                key={name}
                className="flex items-center gap-2 font-semibold opacity-70 hover:opacity-100 transition-opacity">
                
                  <Icon className="h-5 w-5" />
                  <span>{name}</span>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Background decorative elements */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-full overflow-hidden -z-10 pointer-events-none">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] rounded-full bg-purple-300/20 blur-3xl"></div>
        <div className="absolute top-[20%] right-[-10%] w-[30%] h-[50%] rounded-full bg-blue-300/20 blur-3xl"></div>
      </div>
    </div>);

}
